### ISSUE TITLE
Google mobile friendly test problemi

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#1]
Provukao sam sajt kroz Google mobile-frienly test I cini se da ima problema sa header slikom i jos neke sitnice.

https://search.google.com/test/mobile-friendly/result?id=TocNPp2okoM4hB9HShJbDg

**Comment by pavlenex** [comment]
Hero image mozda more da bude "cover"

Evo nove slike koju je dizajner poslao.

![bitcoin-island-min](https://user-images.githubusercontent.com/36959754/190873599-ee16b76f-5e10-4421-a825-c9e050521761.jpg)

**Comment by Djo1e** [comment]
@pavlenex Nisam siguran zbog cega mobile-friendly test izbacuje ovo. Testirao sam na vise uredjaja i generalno je svuda izgledalo okej. Jel ti se desilo da negde ne izgleda dobro?

Dok sam pokusavao da sredim gresku, sredio sam lighthouse score u medjuvremenu 😄

| Pre      | Posle |
| ----------- | ----------- |
| ![Screenshot 2022-09-18 at 19 43 21](https://user-images.githubusercontent.com/34274884/192163207-9f20c9d6-6c77-4480-bfb0-936463ea65ed.png)    |  ![Screenshot 2022-09-25 at 17 42 21](https://user-images.githubusercontent.com/34274884/192163210-98fdab96-4327-4078-b61d-144d2f56508c.png)      |

Neka ostane otvoren ovaj issue, vraticu mu se u nekom trenutnu.

**Comment by pavlenex** [comment]
@Djo1e Meni izgleda okej na iPhone13/Safari. Mozda samo hamburger meni. Mozda i da font bude malo veci? Ne znam da li postoji neka najbolja praksa sto se toga tice?![image](https://user-images.githubusercontent.com/36959754/192377408-37cd05b6-5c83-4af6-a5cc-d68df8f7c972.png)

**Comment by Djo1e** [comment]
Dobar predlog, dodacu hambuger meni i povecati font. Ne postoji dizajn za mobile pa sam u hodu improvizovao.

**Comment by Djo1e** [comment]
@pavlenex Font povecan, hamburger meni dodat, mobile-friendly test prolazi 👍

![Screenshot 2022-10-12 at 17 54 14](https://user-images.githubusercontent.com/34274884/195390724-a1618443-08ba-4a10-b4e0-7f2d9ff34faa.png)

**Comment by pavlenex** [comment]
Odlicno, mozemo zatvoriti ovo!
