### ISSUE TITLE
Klik na dvadesetjedan logo/title ne vodi na home na mobilnom

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#16]
Probao na Safariju iphone 13, klik na logo ili title-u ne vodi na homepage![image](https://user-images.githubusercontent.com/36959754/201757458-dbef8104-d92a-46f7-bf60-d6fb9931f3f7.jpeg)

**Comment by Djo1e** [comment]
Popravljeno
