### ISSUE TITLE
Undefined bug umesto liste podcasta

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#17]
![image](https://user-images.githubusercontent.com/36959754/201757655-2e7d40f8-7180-45e7-b21b-385cbcd8ba22.jpeg)

![image](https://user-images.githubusercontent.com/36959754/201757689-7b4acdd3-944a-4f45-9561-a49464b9e89c.jpeg)

**Comment by Djo1e** [comment]
Popravljeno. Jel mozes da testiras da li je ok kod tebe?

**Comment by Djo1e** [comment]
> Trebalo bi implementirati tile view sto se dizajna tice. 

Implementiran je tile view sve ekrane preko 900px. Na telefonu ne moze da stane tile view, tj izgledalo bi bas cudno.

**Comment by pavlenex** [comment]
Super je sada!
