### ISSUE TITLE
Implementirati photoswipe kao gallery view

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#18]
Trenutno, gallery view se ne poklapa na Figma dizajnu, ovo je posebno vidljivo na mobilnom uredjaju. Trebalo bi implementirati https://photoswipe.com/
![image](https://user-images.githubusercontent.com/36959754/201758073-759f9090-620b-4502-adbe-af8156a16414.jpeg)

**Comment by Djo1e** [comment]
Nisam siguran da je neophodno uvoditi dodatni lib za ovo. Vise bi mi vremena trebalo za to. Jel mozes da pogledas da li ti sada dobro izgleda?

**Comment by pavlenex** [comment]
Da, deluje mi sada skroz ok!
