### ISSUE TITLE
Dodati link u naslovnoj slici i naslovu

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#2]
Link treba biti u featured slici i naslovu na blog stranici radi laskeg pristupa sadrzaju.![image](https://user-images.githubusercontent.com/36959754/196531960-d4e2fe85-55ef-4e7a-a2d9-f6fa855cdf3d.jpeg)

**Comment by Djo1e** [comment]
Popravljeno u https://github.com/Dvadeset-Jedan/dvadesetjedan.com/commit/458229e346fa99c00834b512b3babb971106a472
