### ISSUE TITLE
Rotirati `blog` i `meetup` sekciju na pocetnoj strani

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#41]
@Djo1e Sta mislis da izvrsimo rotaciju meetup i blog sekcije na homepage-u?

Nekako mi se cini da ce su ti featured tekstovi koje imamo mozda bitni siroj publici od meetupa? 

Ako mislis da ne treba, i to je okej, nemam jaku preferenciju, samo generalno pitanje sta ti mislis.

![Screenshot 2022-11-27 at 13 24 34](https://user-images.githubusercontent.com/36959754/204135171-567ba26c-40c6-40bc-8071-e114076a1051.png)

**Comment by Djo1e** [comment]
slazem se, izgleda bolje kada je blog prvi 👍
