### ISSUE TITLE
Zamena barcode logo-a?

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#42]
Ovaj barcode logo koji imamo je kul ali nikako nema veze sa grupom ili bitcoinom, da li da probamo da ga zamenimo logoom koji je Bitko poslao?

![BY_-_DJ_logo_(850px_wide)](https://user-images.githubusercontent.com/36959754/204135229-9e199f82-af6e-4a45-8668-6991edeeedf2.png)
![BY_-_DJ_logo](https://user-images.githubusercontent.com/36959754/204135231-c14cdb05-1b08-4211-b60e-56c9f498b91c.svg)

**Comment by Djo1e** [comment]
promenjeno
