### ISSUE TITLE
Istražiti Anchor.fm API za dodavanje podcast epizoda automatski

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#5]
Trenutno se podcast epizode dodaju ručno, Djole je pomenuo da treba istražiti da li Anchor API dozvoljava da to odradimo besplatno. Evo ga tiket da ne zaboravimo na to 😄

**Comment by Djo1e** [comment]
Skroz sam zaboravio da taj deo verovatno ne moramo rucno. Anchor ima RSS. Povezao sam sve sada 🎉 Baci pogled da li ti sve deluje okej, pa mozes zatvoriti issue ako je 👍

**Comment by pavlenex** [comment]
Bravo, dobro je sad sve, zatvaram 🚀
