### ISSUE TITLE
Dodati jezik flag za blog postove

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#6]
Neki tekstovi su na sr, drugi na hr, neki ce biti bh, mn,  tako da mozda ne bi bilo lose da smislimo nacin da pored autora imamo flag koji ce omoguciti ljudima da cisto znaju da je sajt na razliciitm jezicima, flag moze biti obican emoji, sta mislite? 
Autor: Gigi Prevod: Matija 🇭🇷
i kad se klikne možda filtrira po jeziku? 

Znam da je pitanje jezika i razumevanja glupo, samo bi bilo kul da ljudi znaju da očekuju miks jezika iz cele eks-yu

**Comment by Djo1e** [comment]
@pavlenex dodato

**Comment by pavlenex** [comment]
Bravo Djole, to je to!
