### ISSUE TITLE
Dvadesetjedan.com je offline 🚨

### ISSUE THREAD

**Issue by Djo1e** [Dvadeset-Jedan/dvadesetjedan.com#71]
@pavlenex Izgleda da opet imamo problema sa domain-om. 

<img width="1065" alt="Screenshot 2023-05-02 at 13 15 39" src="https://user-images.githubusercontent.com/34274884/235651914-8dd05ab0-7685-4567-bfcd-6238ad590351.png">

**Comment by pavlenex** [comment]
@Djo1e Meni radi, mozda je nesto kratkorocno?

**Comment by Djo1e** [comment]
@pavlenex izgleda tako, sada je ok 👍
