### ISSUE TITLE
`Copy link` na blogu ne daje utisak da je nesto iskopirano

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#8]
Kada se klikne na Copy Link (koji btw treba prevesti), ne dobija se nikakav feedback da je akcija uspesna, trebalo bi dodati nekakav nacin koji ce ili reci copied ili overlay da se nesto stvarno desilo.

Mala stvar koji sam primetio, nije prioritet sigurno

![Screenshot 2022-10-20 at 18 30 03](https://user-images.githubusercontent.com/36959754/197006395-e5e49684-c66d-4cc6-bea7-b980f96a17d7.png)

**Comment by Djo1e** [comment]
@pavlenex dodato
