### ISSUE TITLE
Dodati preview image za drustvene mreze

### ISSUE THREAD

**Issue by pavlenex** [Dvadeset-Jedan/dvadesetjedan.com#9]
Trenutno kada se clanak podeli na Twitteru npr nema social media preview slike, bilo bi super to dodati.
![Screenshot 2022-10-20 at 18 33 13](https://user-images.githubusercontent.com/36959754/197006850-f5b144bf-09b7-486c-8946-f91b526418ea.png)

**Comment by Djo1e** [comment]
Pogledacu ovaj issue kada se prebacimo na pravi domain. Moguce da je do toga.

**Comment by pavlenex** [comment]
Izgleda da nije do domena https://www.opengraph.xyz/url/https%3A%2F%2Fdvadesetjedan.com%2Fblog%2Flatin-american-bitcoin-perspective

**Comment by pavlenex** [comment]
I ovo bi valjalo popraviit 

![Screenshot 2022-12-16 at 18 29 30](https://user-images.githubusercontent.com/36959754/208155046-78788fe8-4b09-471f-af5d-56468512774d.png)

**Comment by Djo1e** [comment]
<img width="150" alt="Screenshot 2023-04-20 at 21 33 15" src="https://user-images.githubusercontent.com/34274884/233469551-ef632746-c9a3-409e-a4a3-1cc1b2c43f77.png">


<img width="513" alt="Screenshot 2023-04-20 at 21 35 58" src="https://user-images.githubusercontent.com/34274884/233470122-59efe9f7-3f0b-4f95-b4be-78174d094f20.png">
